[package]
name = "quickstudy"
version = "0.1.0"
edition = "2021"

[dependencies]
ncurses = {version = "5.101.0", optional = true}

# [target.'cfg(not(windows))'.features]
# default = ["tui", "ncurses"]

[features]
tui = ["ncurses"]
default = ["tui"]
